### ISSUE TITLE
does not find repositories

### ISSUE THREAD

**Issue by asafbennatan** [juhaku/juhakudb#1]
Hi,
when calling 

```
   DatabaseManager databaseManager = new DatabaseManager(this, new DatabaseConfigurationAdapter() {
            @Override
            public void configure(DatabaseConfiguration configuration) {
                configuration.getBuilder().setBasePackages("com.example.pacakge.model", "com.example.pacakge.model.repositories")
                        .setVersion(1) // Updating this version will cause database to update.
                        .setName("example.db")
                        .setMode(SchemaCreationMode.UPDATE)
                        .setAllowRollback(false)
                        .setRollbackHistorySize(5) // Number of back-ups allowed to take from database schema.
                        .setEnableAutoInject(true) // This will enable annotation based repository injection.
                        .setRepositoryLocations("com.example.pacakge");
            }
        });
```

repositories are not being injected or created manually , looking the the databasemanager i can see that resolveClasses could not find the relevant classes as it iterates the wrong dex file, iterating over
`context.getApplicationInfo().splitSourceDirs` will solve the issue.
im currently trying to fix this but cant bulild the project.
Thanks.

**Comment by juhaku** [comment]
Hi thanks for feedback. Sorry to reply this late but I will look into this. I will put it to the queue as next. I have older test project which works as it is. But propbably things has changed in a year quite a lot. :/

**Comment by juhaku** [comment]
It's being now fixed.. True running the project needs specific setup.. So I'm afraid that it is not possible easily
